DTSAM-281 Spring Boot 3 Upgrade - upgrades to reformS2sClient, spring…
hmcts/am-judicial-booking-service pull request #1058
Opened 2024-05-03 15:30 UTC by mikebrownccd

https://tools.hmcts.net/jira/browse/DTSAM-281
Spring Boot 3 Upgrade - upgrades to reformS2sClient, springBoot, spring, springSecurity, tomcat, logback

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] Does this PR introduce a breaking change

2025-03-12 11:16 UTC, AntonyLeons commented on src/main/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingApplication.java
> +//        "uk.gov.hmcts.reform.idam", "uk.gov.hmcts.reform.authorisation"})
think you can delete this

2025-03-12 11:24 UTC, AntonyLeons commented on src/main/resources/application.yaml
> +      enabled: false
is false intentional?

2025-03-12 11:27 UTC, AntonyLeons approved these changes

2025-04-16 14:43 UTC, kiran-yenigala-hmcts commented on src/main/resources/application.yaml
> +      enabled: false
changed to true

2025-05-12 14:37 UTC, mattnayler requested changes

2025-05-13 08:57 UTC, kiran-yenigala-hmcts commented on src/main/resources/application.yaml
> +    root: DEBUG
removed and reverted to old value

2025-05-13 09:39 UTC, kiran-yenigala-hmcts commented on pacts/accessMgmt_judicialBooking-am_orgRoleMapping_refresh.json
> +{
removed it now

2025-05-16 14:11 UTC, mattnayler commented on pacts/accessMgmt_judicialBooking-am_orgRoleMapping_refresh.json
> +{
Resolved in e30cb0e2c73bcd74e7cf9e052dd9f1f904e92d81.

2025-05-16 14:11 UTC, mattnayler commented on src/main/resources/application.yaml
> +    root: DEBUG
Resolved in e30cb0e2c73bcd74e7cf9e052dd9f1f904e92d81.

2025-05-20 10:03 UTC, mattnayler commented on src/main/resources/application.yaml
> +        include: health,info,data-extract
Can we drop `data-extract` from here

2025-05-29 10:26 UTC, kiran-yenigala-hmcts commented on src/main/resources/application.yaml
> +        include: health,info,data-extract
removed

2025-05-29 10:55 UTC, mattnayler commented on src/main/resources/application.yaml
> +        include: health,info,data-extract
Resolved in a264b1e0bde5de7e30b8c98f7c1687bfce0443af.

2025-05-29 10:57 UTC, mattnayler submitted a review, later dismissed

2025-06-06 12:16 UTC, mattnayler commented on build.gradle
> +    smokeTestImplementation 'com.github.hmcts:fortify-client:1.4.1:all'
Resolved in d48899a676dd38670997154b99e2fe6b8c17228a.

2025-06-06 12:18 UTC, mattnayler approved these changes
Re-approved after conflict resolution, 3ed058fc533855eb10f10133193372bf32e2a99e & d48899a676dd38670997154b99e2fe6b8c17228a.

2025-06-12 13:39 UTC, AntonyLeons approved these changes

2025-06-12 13:54 UTC, mattnayler approved these changes
Re-approved after conflict resolution, b4f42ac00a4975400af62c194ac477c654f9a8ea.

2025-06-25 15:14 UTC, mattnayler approved these changes
Re-approved after CVE fix (56a718c9aae77e98bb7529b2407889850f5273ad)

2025-06-25 15:50 UTC, rapolaskaseliscgi commented on build.gradle
> +        junitPlatform      : '1.11.3',
These technically shouldn't be managed by ourselves, as it can create incompatibility. If I am not mistaken, with spring-boot-starter-test they are included. And SB3.3 use junit version 5.10.5 (and 1.10.5)

2025-06-25 15:52 UTC, rapolaskaseliscgi commented on build.gradle
> +    implementation group: 'org.springframework.security', name: 'spring-security-oauth2-resource-server'
I don't think any of these are needed. They are sub-dependencies of spring-boot-starter-{security,oauth2-client,oauth2-resource-server}.

2025-06-25 16:07 UTC, kiran-yenigala-hmcts commented on build.gradle
> +    implementation group: 'org.springframework.security', name: 'spring-security-oauth2-resource-server'
removed these

2025-06-25 16:07 UTC, kiran-yenigala-hmcts commented on build.gradle
> +implementation group: 'io.projectreactor', name: 'reactor-core', version: '3.7.4'
corrected

2025-06-25 16:08 UTC, kiran-yenigala-hmcts commented on build.gradle
> +    contractTestRuntimeOnly group: 'au.com.dius.pact.consumer', name: 'java8',  version: versions.pact_version
I think we need these

2025-06-25 16:44 UTC, rapolaskaseliscgi submitted a review, later dismissed

2025-06-26 07:55 UTC, rapolaskaseliscgi commented on build.gradle
> +    contractTestRuntimeOnly group: 'au.com.dius.pact.consumer', name: 'java8',  version: versions.pact_version
Build failed, but simply because with java8 removal, all consumer libs were removed. You need to add these two libs:
* au.com.dius.pact:consumer
* au.com.dius.pact.consumer:junit5

2025-06-26 07:57 UTC, rapolaskaseliscgi commented on build.gradle
> +    contractTestRuntimeOnly group: 'au.com.dius.pact.consumer', name: 'java8',  version: versions.pact_version
Sorry, I think, I wasn't clear on my initial comment. I believe, we don't need java8 library, but we do need consumer libraries.

2025-06-26 09:25 UTC, mattnayler approved these changes
Re-approved after recent dev review changes.

2025-06-26 14:34 UTC, merged